# Generated by Django 2.2.2 on 2022-04-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
