# Generated by Django 2.2.2 on 2022-04-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20220405_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order_Number',
            field=models.CharField(default=0, max_length=122),
            preserve_default=False,
        ),
    ]
