# Generated by Django 2.2.2 on 2022-04-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Number', models.CharField(max_length=122)),
                ('items', models.CharField(max_length=122)),
                ('paymentid', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
